name: map
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - jupyter
  - matplotlib
  - seaborn
  - pip:
    - langchain
    - langchain-community
    - langchain-experimental
    - openai
    - duckduckgo-search
    - pandas 
    - pyarrow
    - tqdm