name: map-project
channels:
  - defaults
  - conda-forge
  - huggingface
dependencies:

  - python=3.10
  - pip
  - pandas
  - pyarrow
  - jupyter 
  - matplotlib 
  - seaborn 
  - datasets
  - tqdm
  - pip:
    - langchain
    - langchain-community
    - langchain_experimental
    - openai
    - duckduckgo-search
